# Generated by Django 5.1.5 on 2025-01-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_yazilarmodel_icerik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazilarmodel',
            name='resim',
            field=models.ImageField(upload_to='yazi_resimleri'),
        ),
    ]
